"""Add sync_status columns and notification_settings table

Revision ID: 1b0341bc76bd
Revises: 
Create Date: 2025-04-04 10:52:29.967299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0341bc76bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_cases', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_cases', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('closed_cases', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_calls', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.drop_column('api_calls')
        batch_op.drop_column('closed_cases')
        batch_op.drop_column('updated_cases')
        batch_op.drop_column('new_cases')

    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('notification_settings')
    # ### end Alembic commands ###
